# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
podfile: XCFit2Demo/Podfile

script:
 - cd XCFit2Demo/
 - pwd
 - set -o pipefail && xcodebuild -list
 - bundle install
 - echo "==========Now Running XCUI Cucumberish Tests==================="
 - bundle exc fastlane xcfit_ui_test
